### Insert
POST http://localhost:8080/accounts/create
Content-Type: application/json

{
  "name": "raul"
}

### Insert
POST http://localhost:8080/accounts/create
Content-Type: application/json

{
  "name": "raul311"
}

### Insert
POST http://localhost:8080/accounts/create
Content-Type: application/json

{
  "name": "aaaaaaaaaaaaaaaaaa"
}